"use client";
import { useEffect, useState } from "react";
import {request} from "@/lib/backend";
const control="border rounded-lg px-3 py-2 w-full";
type MonitoringData = {costComparison: null | {source:string; asOf:string; unit:string; quantity:number;rateCr:number;variancePct:number;warning:string};
  duplicateWorkCandidates:{projectId:string;name:string;distanceKm:number;possibleSplitWork:boolean}[];
  recordCompleteness:{score:number;definition:string;checks:{label:string;passed:boolean}[]};limits:string[]};
type History={recordedAt:string;source:string;spentCr:number;physicalProgressPct:number};
type Milestone={id:number;label:string;date:string;status:string};
export default function Monitoring({base,token,pid,canManage}:{base:string;token:string;pid:string;canManage:boolean}) {
  const [data,setData]=useState<MonitoringData|null>(null),[history,setHistory]=useState<History[]>([]),[milestones,setMilestones]=useState<Milestone[]>([]);
  const [error,setError]=useState(""),[busy,setBusy]=useState(false);
  async function refresh() {
    const [d,h,m]=await Promise.all([request<MonitoringData>(base,token,"/projects/"+pid+"/monitoring"),request<History[]>(base,token,"/projects/"+pid+"/financial-history"),request<Milestone[]>(base,token,"/projects/"+pid+"/timeline")]);
    setData(d);setHistory(h);setMilestones(m);
  }
  useEffect(()=>{setData(null);setError("");refresh().catch(e=>setError(e.message));},[base,token,pid]); // eslint-disable-line react-hooks/exhaustive-deps
  async function save(path:string,body:unknown) {setBusy(true);setError("");try {await request(base,token,path,{method:"POST",body:JSON.stringify(body)});await refresh();}catch(e){setError(e instanceof Error?e.message:"Save failed");}finally{setBusy(false);}}
  return <div className="space-y-5 border-t pt-5">
    <h3 className="text-lg font-bold">Monitoring checks</h3>{error&&<p role="alert" className="text-red-700">{error}</p>}
    {data&&<><div className="grid md:grid-cols-2 gap-4"><section className="border rounded-xl p-4"><h4 className="font-semibold">Record completeness · {data.recordCompleteness.score}/100</h4><ul className="mt-3 space-y-2 text-sm">{data.recordCompleteness.checks.map(c=><li key={c.label}>{c.passed?"✓":"○"} {c.label}</li>)}</ul><p className="text-xs text-slate-500 mt-3">{data.recordCompleteness.definition}</p></section>
      <section className="border rounded-xl p-4"><h4 className="font-semibold">Possible duplicate / split work</h4>{data.duplicateWorkCandidates.length?data.duplicateWorkCandidates.map(c=><p key={c.projectId} className="text-sm mt-3">{c.name} (#{c.projectId}) · {c.distanceKm} km · {c.possibleSplitWork?"Overlapping dates and same agency; review scope boundaries":"Similar name, sector and location"}</p>):<p className="text-sm text-slate-500 mt-3">No candidates in the accessible nearby records.</p>}<p className="text-xs text-slate-500 mt-3">{data.limits.join(" ")}</p></section></div>
      <section className="rounded-xl bg-slate-50 p-4"><h4 className="font-semibold">Cost benchmark comparison</h4>{data.costComparison?<><p className="mt-2">Sanctioned cost is {data.costComparison.variancePct}% above/below the supplied benchmark total.</p><p className="text-sm mt-2">{data.costComparison.quantity} {data.costComparison.unit} × ₹{data.costComparison.rateCr} Cr · {data.costComparison.source} · {data.costComparison.asOf}</p><p className="text-xs text-slate-500 mt-2">{data.costComparison.warning}</p></>:<p className="text-sm mt-2">No comparable benchmark entered. Cost inflation cannot be estimated from expenditure alone.</p>}
      {canManage&&<details className="mt-3"><summary className="cursor-pointer text-blue-700">Record a sourced benchmark</summary><form className="grid sm:grid-cols-2 gap-3 mt-3" onSubmit={e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>;save("/projects/"+pid+"/cost-benchmark",{...v,quantity:Number(v.quantity),rateCr:Number(v.rateCr)});}}>
        {[['quantity','Quantity','number'],['unit','Unit (e.g. classroom)','text'],['rateCr','Comparable cost per unit (crore)','number'],['asOf','Benchmark date','date'],['source','Source reference','text'],['comparabilityNote','Why specifications, location and full scope match','text']].map(([name,label,type])=><label key={name} className="text-sm">{label}<input required className={control} name={name} type={type} step="any"/></label>)}<button className="rounded-lg bg-blue-700 text-white p-2" disabled={busy}>Save benchmark</button></form></details>}</section></>}
    <details><summary className="font-semibold cursor-pointer">Recorded progress and spending history ({history.length})</summary><div className="overflow-x-auto"><table className="w-full text-sm mt-3 text-left"><thead><tr><th>Date</th><th>Source</th><th>Spent (Cr)</th><th>Physical progress</th></tr></thead><tbody>{history.map((h,i)=><tr key={i}><td className="py-2">{new Date(h.recordedAt).toLocaleString()}</td><td>{h.source}</td><td>{h.spentCr}</td><td>{h.physicalProgressPct}%</td></tr>)}</tbody></table>{!history.length&&<p>No revision history yet. New updates will appear here.</p>}</div></details>
    <details><summary className="font-semibold cursor-pointer">Milestones ({milestones.length})</summary><ul className="text-sm space-y-2 mt-3">{milestones.map(m=><li key={m.id}>{m.date} · {m.label} · {m.status}</li>)}</ul>{canManage&&<form className="grid sm:grid-cols-3 gap-3 mt-3" onSubmit={e=>{e.preventDefault();save("/projects/"+pid+"/timeline",Object.fromEntries(new FormData(e.currentTarget)));}}><label>Milestone<input required name="label" className={control}/></label><label>Date<input required type="date" name="date" className={control}/></label><label>Status<select name="status" className={control}>{['Pending','In Progress','Completed','Delayed'].map(s=><option key={s}>{s}</option>)}</select></label><button className="rounded-lg bg-blue-700 text-white p-2" disabled={busy}>Add milestone</button></form>}</details>
  </div>;
}
